######################################################################
# Automatically generated by qmake (2.01a) ven. mars 10 10:46:43 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += budgetmodule.h mainwindow.h module.h
FORMS += mainwindow.ui
SOURCES += budgetmodule.cpp main.cpp mainwindow.cpp module.cpp
